# Generated by Django 4.0.6 on 2022-07-06 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('humidity', models.CharField(max_length=50)),
                ('pressure', models.CharField(max_length=50)),
                ('precipitation', models.CharField(max_length=50)),
                ('snowfall', models.CharField(max_length=50)),
                ('total_cloud_cover', models.CharField(max_length=50)),
                ('cloud_cover_high', models.CharField(max_length=50)),
                ('cloud_cover_mid', models.CharField(max_length=50)),
                ('cloud_cover_low', models.CharField(max_length=50)),
                ('shortwave_radiation', models.CharField(max_length=50)),
                ('wind_speed_10', models.CharField(max_length=50)),
                ('wind_direction_10', models.CharField(max_length=50)),
                ('wind_speed_80', models.CharField(max_length=50)),
                ('wind_direction_80', models.CharField(max_length=50)),
                ('wind_gusts', models.CharField(max_length=50)),
                ('sun_altitude', models.CharField(max_length=50)),
                ('sun_zenith', models.CharField(max_length=50)),
                ('sun_distance', models.CharField(max_length=50)),
                ('sun_azimuth', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=5)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feels_like', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
